routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'MainController@index')->name('main');

Route::get('shop', 'ShopController@shop')->name('shop');
Route::get('shop_', 'ShopController@shop_')->name('shop_');
Route::get('shop__', 'ShopController@shop__')->name('shop__');

Route::resource('pages', 'PageController')->only('show');

Route::get('articles/mini', 'BlogController@mini')->name('articles.mini');
Route::resource('articles', 'BlogController')->only('index', 'show');

/*auth*/
Route::middleware(['auth', 'count.balance'])->group(function () {

    Route::post('/buy/coins', 'BuyCoinsController@addBalance')->name('buy.coins');

    Route::get('/bank', 'BankController@bank')->name('bank');
    Route::post('/bank/exchange', 'BankController@exchange')->name('bank.exchange');

    Route::get('mines', 'MineController@index')->name('mines');
    Route::get('/blackjack', 'BlackJackController@blackjack')->name('blackjack');
    Route::get('/poker/holdem', 'PokerController@start')->name('poker.holdem');
    Route::get('stone/pharaoh', 'Games\Stones\PharaohController@index')->name('stone.pharaoh');

    Route::get('/home', 'UserController@show')->name('home');

    Route::resource('user', 'UserController')->only('show','edit', 'update');

    Route::prefix('games')->name('games.')->namespace('Games')->group(function () {

        Route::prefix('slots')->name('slots.')->namespace('Slots')->group(function () {
            Route::resource('cats', 'CatsController')->only('show', 'store');
            Route::get('cats', 'CatsController@store');
        });

        Route::prefix('/stone')->name('stones.')->namespace('Stones')->group(function () {
            Route::post('pharaoh/game', 'PharaohController@game')->name('pharaoh.game');
            Route::get('pharaoh/game', 'PharaohController@game')->name('pharaoh.game');
        });

        Route::prefix('/mines')->name('mines.')->namespace('Mines')->group(function () {
            Route::post('/', 'MineController@mine')->name('check');
            Route::post('get', 'MineController@getCash')->name('get');
        });

        Route::prefix('/blackjack')->name('blackjack.')->namespace('BlackJack')->group(function () {
            Route::post('/getCard', 'BlackJackController@getCard')->name('get_card');
            Route::post('/start', 'BlackJackController@start')->name('start');
            Route::post('/stop', 'BlackJackController@stop')->name('stop');
        });

    });

    Route::post('comments/store/{article}', 'BlogController@add_comments')->name('comments.store');
    Route::post('comments/like/{comment}', 'BlogController@like_comments')->name('comments.like');
    Route::post('comments/update/{comment}', 'BlogController@update_comments')->name('comments.update');
    Route::post('comments/delete/{comment}', 'BlogController@delete_comments')->name('comments.delete');
});


#region Admin
Route::group(['prefix' => 'admin', 'middleware' => [
    'auth',
    'role:moderator'
], 'namespace' => 'Admin', 'as' => 'admin.'], function () {

    /*default*/
    Route::get('/', 'MainController@index')->name('main');
    Route::resource('users', 'UserController')->only('index', 'edit'); //*
    Route::resource('sessions', 'SessionController')->only('index'); //*


    /*E-commerce*/
    Route::get('categories/place', 'CategoryController@place')->name('categories.place');
    Route::resource('categories', 'CategoryController')->only('index', 'edit');

    Route::resource('products', 'ProductController')->only('index', 'edit', 'show');
    Route::resource('rates', 'RateController')->only('index', 'edit', 'show');
    Route::resource('orders', 'OrderController')->only('index', 'edit');
    Route::resource('payments', 'PaymentController')->only('index', 'edit');
    Route::resource('carts', 'CartController')->only('index', 'edit');


    /*Content*/
    Route::resource('pages', 'PageController')->only('index', 'edit', 'show');
    Route::resource('menus', 'MenuController')->only('index', 'edit');
    Route::resource('news', 'NewController')->only('index', 'edit', 'show');

    Route::resource('article-categories', 'ArticleCategoryController')->only('index', 'edit'); //*
    Route::get('article-categories/place', 'ArticleCategoryController@place')->name('article-categories.place'); //*

    Route::resource('articles', 'ArticleController')->only('index', 'edit', 'show');
    Route::resource('texts', 'TextController')->only('index', 'edit', 'show');


    /*Settings*/
    Route::resource('settings', 'SettingController')->middleware('role:admin')->only('index', 'edit', 'show');
    Route::resource('api_settings', 'SettingController')->middleware('role:admin')->only('index', 'edit', 'show');
    Route::resource('roles', 'SettingController')->middleware('role:admin')->only('index', 'edit', 'show');
    Route::resource('permissions', 'SettingController')->middleware('role:admin')->only('index', 'edit', 'show');


    /*misc*/
    Route::get('/documentation', 'DocController@index')->name('documentation');

    Route::resource('admin_settings', 'AdminSettingController')->middleware('role:owner')->only('index');

});
#endregion

app/Models/AdminSetting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\AdminSetting
 *
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\AdminSetting newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\AdminSetting newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\AdminSetting query()
 * @mixin \Eloquent
 * @property int $id
 * @property string $key
 * @property int $value
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\AdminSetting whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\AdminSetting whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\AdminSetting whereKey($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\AdminSetting whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\AdminSetting whereValue($value)
 */
class AdminSetting extends Model
{
    //
}

app/Http/Controllers/Admin/AdminSettingController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AdminSettingController extends Controller
{
    public function index()
    {
        return view('admin.admin_setting.index');
    }
}

app/Http/Controllers/Api/Admin/AdminSettingController.php
<?php

namespace App\Http\Controllers\Api\Admin;

use App\Models\AdminSetting;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AdminSettingController extends Controller
{
    public function update(Request $request)
    {

        $settings = $request->all();

        foreach ($settings as $key => $setting){
            $set = AdminSetting::where('key', $key)->first();
            $set->value = $setting;
            $set->save();
        }

        return AdminSetting::all();
    }
}

resources/views/admin/admin_setting/index.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="notification row">
            <div class="col-md-12">
                <nav class="breadcrumb" aria-label="breadcrumbs">
                    <ul>
                        <li><a href="{{ route('admin.main') }}">Админка</a></li>
                        <li><a href="{{ route('admin.admin_settings.index') }}">Настройки админки</a></li>
                    </ul>
                </nav>
            </div>
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <div class="card" style="padding: 15px;">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-6">
                                <h2 style="font-size: 15px; font-weight: 800;">Default</h2>
                                <br>
                                <div class="field">
                                    <b-checkbox v-model="setting['e_commerce_d']">
                                        E-commerce админка
                                    </b-checkbox>
                                </div>
                                <div class="field">
                                    <b-checkbox v-model="setting['blog_d']">
                                        Blog админка
                                    </b-checkbox>
                                </div>
                                <div class="field">
                                    <b-checkbox v-model="setting['session']">
                                        Сесии
                                    </b-checkbox>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <h2 style="font-size: 15px; font-weight: 800;">E-commerce</h2>
                                <br>
                                <div class="field">
                                    <b-checkbox v-model="setting['category']">
                                        Категории (продукты)
                                    </b-checkbox>
                                </div>
                                <div class="field">
                                    <b-checkbox v-model="setting['products']">
                                        Продукты/Сервисы
                                    </b-checkbox>
                                </div>
                                <div class="field">
                                    <b-checkbox v-model="setting['orders']">
                                        Заказы
                                    </b-checkbox>
                                </div>
                                <div class="field">
                                    <b-checkbox v-model="setting['payments']">
                                        Транзакции
                                    </b-checkbox>
                                </div>
                                <div class="field">
                                    <b-checkbox v-model="setting['carts']">
                                        Карзина
                                    </b-checkbox>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-6">
                                <h2 style="font-size: 15px; font-weight: 800;">Content</h2>
                                <br>
                                <div class="field">
                                    <b-checkbox v-model="setting['pages']">
                                        Страницы
                                    </b-checkbox>
                                </div>
                                <div class="field">
                                    <b-checkbox v-model="setting['news']">
                                        Новости
                                    </b-checkbox>
                                </div>
                                <div class="field">
                                    <b-checkbox v-model="setting['article_categories']">
                                        Категории (статьи)
                                    </b-checkbox>
                                </div>
                                <div class="field">
                                    <b-checkbox v-model="setting['articles']">
                                        Статьи
                                    </b-checkbox>
                                </div>
                                <div class="field">
                                    <b-checkbox v-model="setting['texts']">
                                        Текста
                                    </b-checkbox>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <h2 style="font-size: 15px; font-weight: 800;">Settings</h2>
                                <br>
                                <div class="field">
                                    <b-checkbox v-model="setting['settings']">
                                        Настройки
                                    </b-checkbox>
                                </div>
                                <div class="field">
                                    <b-checkbox v-model="setting['api_settings']">
                                        Api-Настройки
                                    </b-checkbox>
                                </div>
                                <div class="field">
                                    <b-checkbox v-model="setting['roles']">
                                        Роли
                                    </b-checkbox>
                                </div>
                                <div class="field">
                                    <b-checkbox v-model="setting['permissions']">
                                        Права
                                    </b-checkbox>
                                </div>
                            </div>
                        </div>
                    </div>


                    <div style="text-align: right;">
                        <a class="button is-success" @click="onSave">
                                <span class="icon is-small">
                                  <i class="fas fa-check"></i>
                                </span>
                            <span>Save</span>
                        </a>
                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection


@push('scripts')
    <script>
        new Vue({
            el: "#content",
            data: {
                setting: @json($admin_settings),
            },
            methods: {
                onSave() {
                    let self = this;
                    axios.put(route('admin.admin_settings.update'), self.setting)
                        .then(function (response) {
                            self.$snackbar.open({
                                duration: 5000,
                                message: `Настройки админки успешно обновлена`,
                                position: 'is-bottom-left',
                                queue: false,
                            })
                        })
                        .catch(function (error) {
                            self.$toast.open({
                                duration: 5000,
                                message: `Во время сохранения произошла какая-то ошибка !`,
                                position: 'is-bottom',
                                type: 'is-danger',
                                queue: false,
                            })
                        });
                }
            }
        });
    </script>
@endpush