routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'MainController@index')->name('main');

Route::get('shop', 'ShopController@shop')->name('shop');
Route::get('shop_', 'ShopController@shop_')->name('shop_');
Route::get('shop__', 'ShopController@shop__')->name('shop__');

Route::resource('pages', 'PageController')->only('show');

Route::get('articles/mini', 'BlogController@mini')->name('articles.mini');
Route::resource('articles', 'BlogController')->only('index', 'show');

/*auth*/
Route::middleware(['auth', 'count.balance'])->group(function () {

    Route::post('/buy/coins', 'BuyCoinsController@addBalance')->name('buy.coins');

    Route::get('/bank', 'BankController@bank')->name('bank');
    Route::post('/bank/exchange', 'BankController@exchange')->name('bank.exchange');

    Route::get('mines', 'MineController@index')->name('mines');
    Route::get('/blackjack', 'BlackJackController@blackjack')->name('blackjack');
    Route::get('/poker/holdem', 'PokerController@start')->name('poker.holdem');
    Route::get('stone/pharaoh', 'Games\Stones\PharaohController@index')->name('stone.pharaoh');

    Route::get('/home', 'UserController@show')->name('home');

    Route::resource('user', 'UserController')->only('show','edit', 'update');

    Route::prefix('games')->name('games.')->namespace('Games')->group(function () {

        Route::prefix('slots')->name('slots.')->namespace('Slots')->group(function () {
            Route::resource('cats', 'CatsController')->only('show', 'store');
            Route::get('cats', 'CatsController@store');
        });

        Route::prefix('/stone')->name('stones.')->namespace('Stones')->group(function () {
            Route::post('pharaoh/game', 'PharaohController@game')->name('pharaoh.game');
            Route::get('pharaoh/game', 'PharaohController@game')->name('pharaoh.game');
        });

        Route::prefix('/mines')->name('mines.')->namespace('Mines')->group(function () {
            Route::post('/', 'MineController@mine')->name('check');
            Route::post('get', 'MineController@getCash')->name('get');
        });

        Route::prefix('/blackjack')->name('blackjack.')->namespace('BlackJack')->group(function () {
            Route::post('/getCard', 'BlackJackController@getCard')->name('get_card');
            Route::post('/start', 'BlackJackController@start')->name('start');
            Route::post('/stop', 'BlackJackController@stop')->name('stop');
        });

    });

    Route::post('comments/store/{article}', 'BlogController@add_comments')->name('comments.store');
    Route::post('comments/like/{comment}', 'BlogController@like_comments')->name('comments.like');
    Route::post('comments/update/{comment}', 'BlogController@update_comments')->name('comments.update');
    Route::post('comments/delete/{comment}', 'BlogController@delete_comments')->name('comments.delete');
});


#region Admin
Route::group(['prefix' => 'admin', 'middleware' => [
    'auth',
    'role:moderator'
], 'namespace' => 'Admin', 'as' => 'admin.'], function () {

    /*default*/
    Route::get('/', 'MainController@index')->name('main');
    Route::resource('users', 'UserController')->only('index', 'edit'); //*
    Route::resource('sessions', 'SessionController')->only('index'); //*


    /*E-commerce*/
    Route::get('categories/place', 'CategoryController@place')->name('categories.place');
    Route::resource('categories', 'CategoryController')->only('index', 'edit');

    Route::resource('products', 'ProductController')->only('index', 'edit', 'show');
    Route::resource('rates', 'RateController')->only('index', 'edit', 'show');
    Route::resource('orders', 'OrderController')->only('index', 'edit');
    Route::resource('payments', 'PaymentController')->only('index', 'edit');
    Route::resource('carts', 'CartController')->only('index', 'edit');


    /*Content*/
    Route::resource('pages', 'PageController')->only('index', 'edit', 'show');
    Route::resource('menus', 'MenuController')->only('index', 'edit');
    Route::resource('news', 'NewController')->only('index', 'edit', 'show');

    Route::resource('article-categories', 'ArticleCategoryController')->only('index', 'edit'); //*
    Route::get('article-categories/place', 'ArticleCategoryController@place')->name('article-categories.place'); //*

    Route::resource('articles', 'ArticleController')->only('index', 'edit', 'show');
    Route::resource('texts', 'TextController')->only('index', 'edit', 'show');


    /*Settings*/
    Route::resource('settings', 'SettingController')->middleware('role:admin')->only('index', 'edit', 'show');
    Route::resource('api_settings', 'SettingController')->middleware('role:admin')->only('index', 'edit', 'show');
    Route::resource('roles', 'SettingController')->middleware('role:admin')->only('index', 'edit', 'show');
    Route::resource('permissions', 'SettingController')->middleware('role:admin')->only('index', 'edit', 'show');


    /*misc*/
    Route::get('/documentation', 'DocController@index')->name('documentation');

    Route::resource('admin_settings', 'AdminSettingController')->middleware('role:owner')->only('index');

});
#endregion

resources/views/frontend/partials/_footer.blade.php
<div class="footer" style="background-color: #1C2519;">
    <div class="text-center">
        <p style="padding: 0; margin: 0;">
            <strong><img src="{{ asset('favicon.ico') }}" width="35" height="35" style="margin-right: 5px;"> {{ config('app.name', 'MineStartProject') }} /  v0.0.1 (alpha)</strong>
        </p>
    </div>
</div>

resources/views/frontend/partials/_modelBuyCoin.blade.php
<div class="modal fade buyCoins" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle" style="color: #333; font-weight: 800;">BUY THE
                    COINS</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    <div class="row">
                        <div class="alert alert-danger d-none w-100" id="coins_add_false" role="alert">
                            Вам нужно пополнить счет что бы купить COINS
                        </div>

                        <div class="alert alert-success d-none w-100" id="coins_add_true" role="alert">
                            На ваш счет добавленно <b id="addCoins">5</b> COINS
                        </div>
                    </div>
                    <div class="row">
                        @foreach($products as $product)
                            <div class="col-md-3 text-center">
                                <img src="{{ $product->imgs[0]->url }}" alt="">
                                <h5 style="color: #333; font-weight: 800;">{{ $product->title }} <br> {{ $product->category->title }}</h5>
                                <button onclick="buyCoin({{ $product->title }})" class="btn btn-success btn-sm">BUY</button>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@if(Route::getCurrentRoute()->getName() == 'mines')
    <script>
        function buyCoin(amount) {
            axios.post(route('buy.coins', {
                amount: amount,
            }))
                .then(function (response) {
                    if(response.data.status == true){
                        $('#coins_add_true').removeClass('d-none');
                        $("#addCoins").text(response.data.add_coins);
                        $("#user_balance").text(response.data.user_balance);

                        balance = response.data.user_balance;
                        checkBalance(balance);

                        setTimeout(function () {
                            $('#coins_add_true').addClass('d-none');
                        }, 5000);
                    } else {
                        $('#coins_add_false').removeClass('d-none');
                        setTimeout(function () {
                            $('#coins_add_false').addClass('d-none');
                        }, 5000);
                    }
                })
                .catch(function (error) {

                });
        }
    </script>
@elseif(Route::getCurrentRoute()->getName() == 'main')
    <script>
        function buyCoin(amount) {
            axios.post(route('buy.coins', {
                amount: amount,
            }))
                .then(function (response) {
                    if(response.data.status == true){
                        $('#coins_add_true').removeClass('d-none');
                        $("#addCoins").text(response.data.add_coins);
                        $("#user_balance").text(response.data.user_balance);

                        cats.user_coins = response.data.user_balance;
                        setCoins(cats.user_coins);

                        setTimeout(function () {
                            $('#coins_add_true').addClass('d-none');
                        }, 5000);
                    } else {
                        $('#coins_add_false').removeClass('d-none');
                        setTimeout(function () {
                            $('#coins_add_false').addClass('d-none');
                        }, 5000);
                    }
                })
                .catch(function (error) {

                });
        }
    </script>
@else
    <script>
        function buyCoin(amount) {
            axios.post(route('buy.coins', {
                amount: amount,
            }))
                .then(function (response) {

                })
                .catch(function (error) {

                });
        }
    </script>
@endif

resources/views/frontend/partials/_nav.blade.php
<nav id="nav" class="navbar navbar-expand-md bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url('/') }}">
            <img src="{{ asset('favicon.ico') }}" width="35" height="35"
                 style="margin-right: 5px;"> {{ config('app.name', 'MineStartProject') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">

            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('stone.pharaoh') }}">{{ __('STONE') }}</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{ route('main') }}">{{ __('SLOTS') }}</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{ route('mines') }}">{{ __('MINES') }}</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{ route('blackjack') }}">{{ __('BLACK JACK') }}</a>
                </li>

                <li class="nav-item dropdown">
                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                        {{ __('POKER') }}
                    </a>

                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

                        <a class="dropdown-item" href="{{ route('poker.holdem') }}">
                            {{ __('HOLDEM') }}
                        </a>

                        <a class="dropdown-item" href="#">
                            {{ __('OMAHA') }}
                        </a>

                    </div>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="#">|</a>
                </li>
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('LOGIN') }}</a>
                    </li>
                    <li class="nav-item">
                        @if (Route::has('register'))
                            <a class="nav-link" href="{{ route('register') }}">{{ __('REGISTER') }}</a>
                        @endif
                    </li>
                @else
                    <li class="nav-item">
                        <button onclick="window.location = route('bank')" type="button" class="nav-link btn btn-primary btn-round p-2">
                            <i class="tim-icons icon-bank"></i> БАНК
                        </button>
                        <button type="button" class="nav-link btn btn-secondary btn-round p-2" id="show_u_b">
                            <i class="tim-icons icon-wallet-43"></i> <b>@json(round(Auth::user()->balance, 4))</b>USD
                        </button>
                    </li>

                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }}
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

                            @if(Auth::user()->hasRole('admin'))
                                <a class="dropdown-item" href="{{ route('admin.main') }}">
                                    {{ __('Admin') }}
                                </a>
                                <hr>
                            @endif

                            <a class="dropdown-item" href="{{ route('user.show', Auth::user()->id) }}">
                                {{ __('Profile') }}
                            </a>

                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                  style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>

resources/views/frontend/partials/_style.blade.php
<style>
    select option{
        background-color: #171941 !important;
        color: #D650D6 !important;
    }

    .dataTables_info{
        color: #ffffff;
    }

    @media only screen and (max-width: 767px) {
        div.dataTables_paginate ul.pagination .page-item:first-of-type, div.dataTables_paginate ul.pagination .page-item:last-of-type, div.dataTables_paginate ul.pagination .page-item:nth-of-type(2), div.dataTables_paginate ul.pagination .page-item:nth-of-type(8) {
            display: list-item!important;
        }
    }

    /*#circle-div{*/
        /*position: fixed;*/
        /*background-color: #151E12;*/
        /*width: 100%;*/
        /*height: 100vh;*/
        /*z-index: 10000;*/
    /*}*/

    /*#circle {*/
        /*position: absolute;*/
        /*top: 50%;*/
        /*left: 50%;*/
        /*transform: translate(-50%,-50%);*/
        /*width: 150px;*/
        /*height: 150px;*/
    /*}*/

    /*.loader {*/
        /*width: calc(100% - 0px);*/
        /*height: calc(100% - 0px);*/
        /*border: 8px solid #6BA73B;*/
        /*border-top: 8px solid #1C2519;*/
        /*border-radius: 50%;*/
        /*animation: rotate 5s linear infinite;*/
    /*}*/

    /*@keyframes rotate {*/
        /*100% {transform: rotate(360deg);}*/
    /*}*/

    /**{*/
        /*transition: all 0.2s ease;*/
    /*}*/

</style>

resources/views/frontend/partials/_up.blade.php
<a id="back-to-top" href="#" class="btn btn-outline-secondary btn-sm back-to-top" role="button"><i class="fas fa-arrow-circle-up"></i></a>