routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'MainController@index')->name('main');

Route::get('shop', 'ShopController@shop')->name('shop');
Route::get('shop_', 'ShopController@shop_')->name('shop_');
Route::get('shop__', 'ShopController@shop__')->name('shop__');

Route::resource('pages', 'PageController')->only('show');

Route::get('articles/mini', 'BlogController@mini')->name('articles.mini');
Route::resource('articles', 'BlogController')->only('index', 'show');

/*auth*/
Route::middleware(['auth', 'count.balance'])->group(function () {

    Route::post('/buy/coins', 'BuyCoinsController@addBalance')->name('buy.coins');

    Route::get('/bank', 'BankController@bank')->name('bank');
    Route::post('/bank/exchange', 'BankController@exchange')->name('bank.exchange');

    Route::get('mines', 'MineController@index')->name('mines');
    Route::get('/blackjack', 'BlackJackController@blackjack')->name('blackjack');
    Route::get('/poker/holdem', 'PokerController@start')->name('poker.holdem');
    Route::get('stone/pharaoh', 'Games\Stones\PharaohController@index')->name('stone.pharaoh');

    Route::get('/home', 'UserController@show')->name('home');

    Route::resource('user', 'UserController')->only('show','edit', 'update');

    Route::prefix('games')->name('games.')->namespace('Games')->group(function () {

        Route::prefix('slots')->name('slots.')->namespace('Slots')->group(function () {
            Route::resource('cats', 'CatsController')->only('show', 'store');
            Route::get('cats', 'CatsController@store');
        });

        Route::prefix('/stone')->name('stones.')->namespace('Stones')->group(function () {
            Route::post('pharaoh/game', 'PharaohController@game')->name('pharaoh.game');
            Route::get('pharaoh/game', 'PharaohController@game')->name('pharaoh.game');
        });

        Route::prefix('/mines')->name('mines.')->namespace('Mines')->group(function () {
            Route::post('/', 'MineController@mine')->name('check');
            Route::post('get', 'MineController@getCash')->name('get');
        });

        Route::prefix('/blackjack')->name('blackjack.')->namespace('BlackJack')->group(function () {
            Route::post('/getCard', 'BlackJackController@getCard')->name('get_card');
            Route::post('/start', 'BlackJackController@start')->name('start');
            Route::post('/stop', 'BlackJackController@stop')->name('stop');
        });

    });

    Route::post('comments/store/{article}', 'BlogController@add_comments')->name('comments.store');
    Route::post('comments/like/{comment}', 'BlogController@like_comments')->name('comments.like');
    Route::post('comments/update/{comment}', 'BlogController@update_comments')->name('comments.update');
    Route::post('comments/delete/{comment}', 'BlogController@delete_comments')->name('comments.delete');
});


#region Admin
Route::group(['prefix' => 'admin', 'middleware' => [
    'auth',
    'role:moderator'
], 'namespace' => 'Admin', 'as' => 'admin.'], function () {

    /*default*/
    Route::get('/', 'MainController@index')->name('main');
    Route::resource('users', 'UserController')->only('index', 'edit'); //*
    Route::resource('sessions', 'SessionController')->only('index'); //*


    /*E-commerce*/
    Route::get('categories/place', 'CategoryController@place')->name('categories.place');
    Route::resource('categories', 'CategoryController')->only('index', 'edit');

    Route::resource('products', 'ProductController')->only('index', 'edit', 'show');
    Route::resource('rates', 'RateController')->only('index', 'edit', 'show');
    Route::resource('orders', 'OrderController')->only('index', 'edit');
    Route::resource('payments', 'PaymentController')->only('index', 'edit');
    Route::resource('carts', 'CartController')->only('index', 'edit');


    /*Content*/
    Route::resource('pages', 'PageController')->only('index', 'edit', 'show');
    Route::resource('menus', 'MenuController')->only('index', 'edit');
    Route::resource('news', 'NewController')->only('index', 'edit', 'show');

    Route::resource('article-categories', 'ArticleCategoryController')->only('index', 'edit'); //*
    Route::get('article-categories/place', 'ArticleCategoryController@place')->name('article-categories.place'); //*

    Route::resource('articles', 'ArticleController')->only('index', 'edit', 'show');
    Route::resource('texts', 'TextController')->only('index', 'edit', 'show');


    /*Settings*/
    Route::resource('settings', 'SettingController')->middleware('role:admin')->only('index', 'edit', 'show');
    Route::resource('api_settings', 'SettingController')->middleware('role:admin')->only('index', 'edit', 'show');
    Route::resource('roles', 'SettingController')->middleware('role:admin')->only('index', 'edit', 'show');
    Route::resource('permissions', 'SettingController')->middleware('role:admin')->only('index', 'edit', 'show');


    /*misc*/
    Route::get('/documentation', 'DocController@index')->name('documentation');

    Route::resource('admin_settings', 'AdminSettingController')->middleware('role:owner')->only('index');

});
#endregion

app/Models/Setting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\Setting
 *
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Setting newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Setting newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Setting query()
 * @mixin \Eloquent
 * @property int $id
 * @property string $setting_category
 * @property string $key
 * @property string $value
 * @property string|null $more
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Setting whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Setting whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Setting whereKey($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Setting whereMore($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Setting whereSettingCategory($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Setting whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Setting whereValue($value)
 */
class Setting extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'setting_category',
        'key',
        'value',
        'more',
    ];
}

app/Http/Controllers/Admin/SettingController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Setting;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SettingController extends Controller
{
    public function index()
    {
        $settings = Setting::all();

        $settings_category = [];
        foreach ($settings as $setting){
            if (!in_array($setting->setting_category, $settings_category)){
                array_push($settings_category, $setting->setting_category);
            }
        }

        return view('admin.setting.index', compact('settings', 'settings_category'));
    }
}

app/Http/Controllers/Api/Admin/SettingController.php
<?php

namespace App\Http\Controllers\Api\Admin;

use App\Models\Setting;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SettingController extends Controller
{
    public function store(Request $request)
    {

        $setting = new Setting();
        $setting->fill($request->all());
        $setting->save();

        $settings = Setting::all();

        $settings_category = [];
        foreach ($settings as $setting){
            if (!in_array($setting->setting_category, $settings_category)){
                array_push($settings_category, $setting->setting_category);
            }
        }


        return [
            'settings_category' => $settings_category,
            'settings'          => $settings
        ];
    }

    public function update(Request $request)
    {

        $settings =$request->all();
        foreach ($settings as $setting){
            $set = Setting::where('key', $setting['key'])->first();
            $set->value = $setting['value'];
            $set->save();
        }


        $settings = Setting::all();

        $settings_category = [];
        foreach ($settings as $setting){
            if (!in_array($setting->setting_category, $settings_category)){
                array_push($settings_category, $setting->setting_category);
            }
        }


        return [
            'settings_category' => $settings_category,
            'settings'          => $settings
        ];
    }
}

resources/views/admin/setting/_form.blade.php
<b-field label="Категория *">
    <b-input v-model="setting.setting_category" style="background-color: #fff;
    border-color: #dbdbdb;
    color: #363636;
    box-shadow: inset 0 1px 2px hsla(0,0%,4%,.1);
    max-width: 100%;
    width: 100%;" list="category"></b-input>
    <datalist id="category">
        <option v-for="s_c in settings_category" :value="s_c">
    </datalist>
</b-field>

<b-field label="Ключ *">
    <b-input v-model="setting.key"></b-input>
</b-field>

<b-field label="Значение *">
    <b-input v-model="setting.value"></b-input>
</b-field>

<b-field label="Дополнение">
    <b-input v-model="setting.more"></b-input>
</b-field>



{{--************************************************--}}
<div style="text-align: right;">
    <a class="button is-success" style="width: 75px;
    float: right;" @click="onSave">
                                <span class="icon is-small">
                                  <i class="fas fa-check"></i>
                                </span>
        <span>Save</span>
    </a>
</div>

resources/views/admin/setting/index.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="notification row">
            <div class="col-md-12">
                <nav class="breadcrumb" aria-label="breadcrumbs" style="display: flex; justify-content: space-between;">
                    <ul style="margin-top: 5px;">
                        <li><a href="{{ route('admin.main') }}">Админка</a></li>
                        <li><a href="{{ route('admin.settings.index') }}">Настройки</a></li>
                    </ul>
                    <div>
                        <button class="button is-success is-smal" @click="onUpdate()">
                            Сохранить настройки
                        </button>
                        <button class="button is-primary is-smal"
                                @click="isCardModalActive = true">
                            Добавить настройку
                        </button>
                    </div>
                    <b-modal :active.sync="isCardModalActive" :width="640" scroll="keep">
                        <div class="card">
                            <div class="card-content">
                                <div class="content">
                                    @include('admin.setting._form')
                                </div>
                            </div>
                        </div>
                    </b-modal>
                </nav>
            </div>

            <div class="card col-md-3" style="padding: 10px;" v-for="sc in settings_category">
                <header class="card-header" style="padding: 0; padding-bottom: 5px; padding-top: 5px;">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-12" style="text-align: center;">
                                <h3><b>@{{ sc }}</b></h3>
                            </div>
                        </div>
                    </div>
                </header>
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12" v-for="setting in settings_list">
                            <b-field v-if="setting.setting_category == sc" :label="setting.key">
                                <b-input v-model="setting.value"></b-input>
                            </b-field>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('styles')
    <style>
        .card{
            transform: scale(0.96);
        }
        .card:hover{
            box-shadow: 1px 1px 5px #333;
        }
    </style>
@endpush

@push('scripts')
    <script>
        new Vue({
            el: "#content",
            data: {
                setting: {},
                isCardModalActive: false,
                settings_list: @json($settings),
                settings_category: @json($settings_category),
            },
            methods: {
                onSave() {
                    let self = this;
                    axios.post(route('admin.settings.store'), self.setting)
                        .then(function (response) {
                            self.setting.key = '';
                            self.setting.value = '';
                            self.setting.more = '';
                            self.settings_category = response.data['settings_category'];
                            self.settings_list = response.data['settings'];
                            self.$snackbar.open({
                                duration: 5000,
                                message: `Настройка успешно добавленна`,
                                position: 'is-bottom-left',
                                queue: false,
                            })
                        })
                        .catch(function (error) {
                            self.$toast.open({
                                duration: 5000,
                                message: `Во время сохранения произошла какая-то ошибка !`,
                                position: 'is-bottom',
                                type: 'is-danger',
                                queue: false,
                            })
                        });
                },
                onUpdate() {
                    let self = this;
                    axios.post(route('admin.settings.update'), self.settings_list)
                        .then(function (response) {
                            self.settings_category = response.data['settings_category'];
                            self.settings_list = response.data['settings'];
                            self.$snackbar.open({
                                duration: 5000,
                                message: `Настройка успешно сохранены`,
                                position: 'is-bottom-left',
                                queue: false,
                            })
                        })
                        .catch(function (error) {
                            self.$toast.open({
                                duration: 5000,
                                message: `Во время сохранения произошла какая-то ошибка !`,
                                position: 'is-bottom',
                                type: 'is-danger',
                                queue: false,
                            })
                        });
                }
            }
        });
    </script>
@endpush