routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'MainController@index')->name('main');

Route::get('shop', 'ShopController@shop')->name('shop');
Route::get('shop_', 'ShopController@shop_')->name('shop_');
Route::get('shop__', 'ShopController@shop__')->name('shop__');

Route::resource('pages', 'PageController')->only('show');

Route::get('articles/mini', 'BlogController@mini')->name('articles.mini');
Route::resource('articles', 'BlogController')->only('index', 'show');

/*auth*/
Route::middleware(['auth', 'count.balance'])->group(function () {

    Route::post('/buy/coins', 'BuyCoinsController@addBalance')->name('buy.coins');

    Route::get('/bank', 'BankController@bank')->name('bank');
    Route::post('/bank/exchange', 'BankController@exchange')->name('bank.exchange');

    Route::get('mines', 'MineController@index')->name('mines');
    Route::get('/blackjack', 'BlackJackController@blackjack')->name('blackjack');
    Route::get('/poker/holdem', 'PokerController@start')->name('poker.holdem');
    Route::get('stone/pharaoh', 'Games\Stones\PharaohController@index')->name('stone.pharaoh');

    Route::get('/home', 'UserController@show')->name('home');

    Route::resource('user', 'UserController')->only('show','edit', 'update');

    Route::prefix('games')->name('games.')->namespace('Games')->group(function () {

        Route::prefix('slots')->name('slots.')->namespace('Slots')->group(function () {
            Route::resource('cats', 'CatsController')->only('show', 'store');
            Route::get('cats', 'CatsController@store');
        });

        Route::prefix('/stone')->name('stones.')->namespace('Stones')->group(function () {
            Route::post('pharaoh/game', 'PharaohController@game')->name('pharaoh.game');
            Route::get('pharaoh/game', 'PharaohController@game')->name('pharaoh.game');
        });

        Route::prefix('/mines')->name('mines.')->namespace('Mines')->group(function () {
            Route::post('/', 'MineController@mine')->name('check');
            Route::post('get', 'MineController@getCash')->name('get');
        });

        Route::prefix('/blackjack')->name('blackjack.')->namespace('BlackJack')->group(function () {
            Route::post('/getCard', 'BlackJackController@getCard')->name('get_card');
            Route::post('/start', 'BlackJackController@start')->name('start');
            Route::post('/stop', 'BlackJackController@stop')->name('stop');
        });

    });

    Route::post('comments/store/{article}', 'BlogController@add_comments')->name('comments.store');
    Route::post('comments/like/{comment}', 'BlogController@like_comments')->name('comments.like');
    Route::post('comments/update/{comment}', 'BlogController@update_comments')->name('comments.update');
    Route::post('comments/delete/{comment}', 'BlogController@delete_comments')->name('comments.delete');
});


#region Admin
Route::group(['prefix' => 'admin', 'middleware' => [
    'auth',
    'role:moderator'
], 'namespace' => 'Admin', 'as' => 'admin.'], function () {

    /*default*/
    Route::get('/', 'MainController@index')->name('main');
    Route::resource('users', 'UserController')->only('index', 'edit'); //*
    Route::resource('sessions', 'SessionController')->only('index'); //*


    /*E-commerce*/
    Route::get('categories/place', 'CategoryController@place')->name('categories.place');
    Route::resource('categories', 'CategoryController')->only('index', 'edit');

    Route::resource('products', 'ProductController')->only('index', 'edit', 'show');
    Route::resource('rates', 'RateController')->only('index', 'edit', 'show');
    Route::resource('orders', 'OrderController')->only('index', 'edit');
    Route::resource('payments', 'PaymentController')->only('index', 'edit');
    Route::resource('carts', 'CartController')->only('index', 'edit');


    /*Content*/
    Route::resource('pages', 'PageController')->only('index', 'edit', 'show');
    Route::resource('menus', 'MenuController')->only('index', 'edit');
    Route::resource('news', 'NewController')->only('index', 'edit', 'show');

    Route::resource('article-categories', 'ArticleCategoryController')->only('index', 'edit'); //*
    Route::get('article-categories/place', 'ArticleCategoryController@place')->name('article-categories.place'); //*

    Route::resource('articles', 'ArticleController')->only('index', 'edit', 'show');
    Route::resource('texts', 'TextController')->only('index', 'edit', 'show');


    /*Settings*/
    Route::resource('settings', 'SettingController')->middleware('role:admin')->only('index', 'edit', 'show');
    Route::resource('api_settings', 'SettingController')->middleware('role:admin')->only('index', 'edit', 'show');
    Route::resource('roles', 'SettingController')->middleware('role:admin')->only('index', 'edit', 'show');
    Route::resource('permissions', 'SettingController')->middleware('role:admin')->only('index', 'edit', 'show');


    /*misc*/
    Route::get('/documentation', 'DocController@index')->name('documentation');

    Route::resource('admin_settings', 'AdminSettingController')->middleware('role:owner')->only('index');

});
#endregion

app/User.php
<?php

namespace App;

use App\Models\Bank;
use App\Models\UserBalance;
use Illuminate\Console\Command;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Auth;

/**
 * App\User
 *
 * @property-read \Illuminate\Notifications\DatabaseNotificationCollection|\Illuminate\Notifications\DatabaseNotification[] $notifications
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Role[] $roles
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User query()
 * @mixin \Eloquent
 * @property int $id
 * @property int|null $user_id
 * @property float $amount_for_ref
 * @property string $slug
 * @property string $avatar
 * @property string $name
 * @property string $email
 * @property float $balance
 * @property int $baned
 * @property string|null $email_verified_at
 * @property string $password
 * @property string|null $remember_token
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereAmountForRef($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereAvatar($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereBalance($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereBaned($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereEmail($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereEmailVerifiedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User wherePassword($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereRememberToken($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereSlug($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereUserId($value)
 * @property int|null $ref_id
 * @property float $bonus
 * @property float $coins
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereBonus($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereCoins($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereRefId($value)
 */
class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id',
        'amount_for_ref',

        'name',
        'slug',
        'email',

        'balance',
        'coins',
        'bonus',

        'baned',

        'password',
    ];

    use Notifiable;

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /****/
    /**
     * Функция для получения названия роли к которой пользователь принадлежит.
     *
     * @return boolean
     **/
    public function roles()
    {
        return $this->belongsToMany('App\Role', 'users_roles', 'user_id', 'role_id');
    }

    /**
     * Проверка принадлежит ли пользователь к какой либо роли
     *
     * @return boolean
     */
    public function isEmployee()
    {
        $roles = $this->roles->toArray();
        return !empty($roles);
    }

    /**
     * Проверка имеет ли пользователь определенную роль
     *
     * @return boolean
     */
    public function hasRole($check)
    {
        //dump($this->roles->toArray());
        //dump(array_pluck($this->roles->toArray(), 'name'));

        return in_array($check, array_pluck($this->roles->toArray(), 'name'));

        // начиная с версии 5.1 метода array_fetch не существует
        //return in_array($check, array_fetch($this->roles->toArray(), 'name'));
    }

    /**
     * Получение идентификатора роли
     *
     * @return int
     */
    private function getIdInArray($array, $term)
    {
        foreach ($array as $key => $value) {
            if ($value == $term) {
                return $key + 1;
            }
        }
        return false;
    }

    public static function getUserName($user)
    {
        return $user->name;
    }

    public function addCoins($user, $amount = 0)
    {
        $user->coins += $amount;
        $user->save();
        return $user->coins;
    }

    public function convertToCoins($currency, $rate, $amount)
    {

    }

    public function balances()
    {
        return $this->hasMany('App\Models\UserBalance', 'user_id', 'id');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Role;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    public function index()
    {
        $roles = Role::all();
        $users = User::with('roles', 'balances')->get();

        return view('admin.user.index', compact('users', 'roles'));
    }

    public function edit(User $user)
    {
        $user = $user->load('roles');
        $roles = Role::all();

        return view('admin.user.edit', compact('user', 'roles'));
    }
}

app/Http/Controllers/Api/Admin/UserController.php
<?php

namespace App\Http\Controllers\Api\Admin;

use App\Http\Requests\UserUpdate;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    public function update(User $user ,UserUpdate $request)
    {
        $user->fill($request->all());
        $user->save();

        return User::with('roles')->get();
    }

    public function search(Request $request)
    {
        return User::where('name', 'like', '%' . $request->search . '%')->orWhere('email', 'like', '%' . $request->search . '%')->with('roles')->get();
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\Games\MineGameLog;
use App\Models\Games\SlotGameLog;
use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function show(User $user, Request $request)
    {
        $mine_games = MineGameLog::whereUserId($user->id)
            ->where('mode', 'pay')->orderBy('id', 'desc')->get();

        $slot_games = SlotGameLog::whereUserId($user->id)
            ->where('mode', 'pay')->orderBy('id', 'desc')->get();

        return view('frontend.auth.home', compact('mine_games', 'slot_games'));
    }
}

resources/views/admin/user/_form.blade.php
<b-field label="Имя"
         :type="errors.name ? 'is-danger' : ''"
         :message="errors.name ? 'Поле обязательно к заполнению' : ''">
    <b-input v-model="user.name" maxlength="50" placeholder="Вася"></b-input>
</b-field>

<b-field label="E-mail"
         :type="errors.email ? 'is-danger' : ''"
         :message="errors.email ? 'Поле обязательно к заполнению' : ''">
    <b-input v-model="user.email" maxlength="50" placeholder="vasy@mail.ru"></b-input>
</b-field>

<div style="text-align: right;">
    <a class="button is-success" @click="onSave">
                                <span class="icon is-small">
                                  <i class="fas fa-check"></i>
                                </span>
        <span>Save</span>
    </a>
</div>

resources/views/admin/user/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="notification row">
            <div class="col-md-12">
                <nav class="breadcrumb" aria-label="breadcrumbs">
                    <ul>
                        <li><a href="{{ route('admin.main') }}">Админка</a></li>
                        <li><a href="{{ route('admin.users.index') }}">Пользователи</a></li>
                        <li><a href="#">Редактирование пользователя: <b>{{ $user->name }}</b></a></li>
                    </ul>
                </nav>
            </div>
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <div class="card" style="padding: 15px;">@include('admin.user._form')</div>
            </div>
        </div>
    </div>
@endsection


@push('scripts')
    <script>
        new Vue({
            el: "#content",
            data: {
                errors: {},
                user: @json($user),
            },
            methods: {
                onSave() {
                    let self = this;
                    axios.put(route('admin.users.update', self.user.id), self.user)
                        .then(function (response) {
                            self.errors = {};
                            self.$snackbar.open({
                                duration: 5000,
                                message: `Пользователь успешно обновлен`,
                                position: 'is-bottom-left',
                                queue: false,
                            })
                        })
                        .catch(function (error) {
                            self.errors= {};
                            let response = error.response;
                            if(response.status === 422) {

                                self.errors = response.data.errors;
                                Object.keys(response.data.errors).map((key) => {
                                    self.errors[key] = response.data.errors[key][0];
                                });
                            }
                            self.$toast.open({
                                duration: 5000,
                                message: `Во время сохранения произошла какая-то ошибка !`,
                                position: 'is-bottom',
                                type: 'is-danger',
                                queue: false,
                            })
                        });
                }
            }
        });
    </script>
@endpush

resources/views/admin/user/index.blade.php
@extends('admin.layouts.app')

@push('styles')
    <style>
        .img-preview-table:hover {
            cursor: pointer;
        }
    </style>
@endpush

@section('content')
    <div class="container-fluid">
        <div class="notification row">

            <div class="col-md-12">
                <nav class="breadcrumb" aria-label="breadcrumbs">
                    <ul>
                        <li><a href="{{ route('admin.main') }}">Админка</a></li>
                        <li><a href="{{ route('admin.users.index') }}">Пользователи</a></li>
                    </ul>
                </nav>
            </div>

            <div class="card col-md-12" style="padding: 5px;">
                <header class="card-header" style="padding: 0; padding-bottom: 5px; padding-top: 5px;">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-4">
                                <b-field
                                    label="Позицый на страницу">
                                    <b-select v-model="per_page" expanded>
                                        <option v-for="item in pre_page_a" :value="item">@{{ item }}</option>
                                    </b-select>
                                </b-field>
                            </div>
                            <div class="col-md-4">
                                <b-field
                                    label="Поиск">
                                    <div class="field has-addons">
                                        <div class="control" style="width: 100%;">
                                            <input class="input" type="text" v-model="filter" placeholder="Поиск">
                                        </div>
                                        <div class="control">
                                            <a class="button is-primary is-outlined" @click="onSearch(filter)">
                                                Найти
                                            </a>
                                        </div>
                                    </div>
                                </b-field>
                            </div>
                            <div class="col-md-4">
                                {{--<button class="button is-primary is-smal"--}}
                                        {{--style="float: right; margin-bottom: 10px; margin-top: 15px;"--}}
                                        {{--@click="isCardModalActive = true">--}}
                                    {{--Добавить товар--}}
                                {{--</button>--}}
                                <b-modal :active.sync="isCardModalActive" :width="640" scroll="keep">
                                    <div class="card">
                                        <div class="card-content">
                                            <div class="content">
                                                @include('admin.user._form')
                                            </div>
                                        </div>
                                    </div>
                                </b-modal>
                            </div>
                        </div>
                    </div>
                </header>
                <b-table
                    :data="data"
                    paginated
                    hoverable
                    mobile-cards
                    :filter="filter"
                    :per-page="per_page"
                    :opened-detailed="defaultOpenedDetails"
                    detailed
                    detail-key="id"
                    @details-open="(row, index) => $toast.open(`Доп.Информация ${row.name} открыта`)">
                    <template slot-scope="props">

                        <b-table-column field="id" label="ID" width="40" sortable numeric>
                            @{{ props.row.id }}
                        </b-table-column>

                        <b-table-column field="img" label="Аватар" width="60" sortable numeric>
                            <img @click="imageModal(props.row.avatar)" class="img-preview-table"
                                 :src="props.row.avatar" alt="" style="height: 30px; width: 45px; object-fit: cover;">
                        </b-table-column>

                        <b-table-column field="name" label="Имя" sortable>
                            @{{ props.row.name }}
                        </b-table-column>

                        <b-table-column field="email" label="Почта" sortable>
                            @{{ props.row.email }}
                        </b-table-column>

                        <b-table-column field="created_at" label="Дата регистрации" sortable>
                            @{{ props.row.created_at }}
                        </b-table-column>


                        <b-table-column field="action" label="" sortable numeric>
                            <div class="btn-group">
                                <a :href="routeEdit+ '/' + props.row.id + '/edit'"
                                   class="btn btn-outline-primary btn-sm">EDIT</a>
                                {{--<button @click="onDelete(props.row.id)" class="btn btn-outline-danger btn-sm">DELETE--}}
                                {{--</button>--}}
                            </div>
                        </b-table-column>
                    </template>
                    <template slot="empty">
                        <section class="section">
                            <div class="content has-text-grey has-text-centered">
                                <p>
                                    <b-icon
                                        icon="emoticon-sad"
                                        size="is-large">
                                    </b-icon>
                                </p>
                                <p>Ничего нет.</p>
                            </div>
                        </section>
                    </template>
                    <template slot="detail" slot-scope="props">
                        <article class="media">
                            <div class="media-content">
                                <div class="content">
                                    <div class="container-fluid">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <p>
                                                    <img
                                                         style="width: 240px; object-fit: cover"
                                                         :src="props.row.avatar">
                                                    <br>
                                                    <br>
                                                    <strong>@{{ props.row.name }}</strong> <sup>@{{
                                                        props.row.roles[0].name }}</sup>
                                                    <br>
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </article>
                    </template>
                </b-table>

            </div>
        </div>
    </div>
@endsection


@push('scripts')
    <script>
        var lfm = function (options, cb) {

            var route_prefix = (options && options.prefix) ? options.prefix : '/laravel-filemanager';

            window.open(route_prefix + '?type=' + options.type || 'file', 'FileManager', 'width=1440,height=960');
            window.SetUrl = cb;
        }
    </script>
    <script>
        var vue = new Vue({
            el: "#content",
            data: {
                routeEdit: route('admin.users.index'),
                filter: '',
                per_page: 10,
                pre_page_a: [5, 10, 20, 50, 100],
                user: {},
                defaultOpenedDetails: [],
                isCardModalActive: false,
                data: @json($users),
                roles: @json($roles),
                errors: {}
            },
            methods: {
                imageModal(url) {
                    this.$modal.open(
                        `<p class="image is-4by3">
                            <img style="object-fit: cover;" src="` + url + `">
                        </p>`
                    )
                },
                lfmm() {
                    let self = this;
                    var img_url = lfm({type: 'image', prefix: ''}, function (url, path) {
                        self.addImgToArray(url);
                    });
                },
                addImgToArray(url) {
                    this.imgs.push({url: url});
                },
                delImgFromArray(key) {
                    this.imgs.splice(key, 1)
                },
                onDelete(index) {
                    let self = this;
                    axios.delete(route('admin.users.destroy', index))
                        .then(function (response) {
                            self.data = response.data;
                            self.$snackbar.open({
                                duration: 5000,
                                message: `Статус продукта успешно изменен`,
                                position: 'is-bottom-left',
                                queue: false,
                            })
                        })
                        .catch(function (error) {
                            self.$toast.open({
                                duration: 5000,
                                message: `Во время сохранения произошла какая-то ошибка !`,
                                position: 'is-bottom',
                                type: 'is-danger',
                                queue: false,
                            })
                        });
                },
                onSave() {
                    let self = this;
                    axios.post(route('admin.users.store'), this.user)
                        .then(function (response) {
                            self.data = response.data;
                            self.user= {};
                            self.errors = {};
                            self.$snackbar.open({
                                duration: 5000,
                                message: `Продукт успешно сохранена`,
                                position: 'is-bottom-left',
                                queue: false,
                            })
                        })
                        .catch(function (error) {
                            self.errors = {};
                            let response = error.response;
                            if(response.status === 422) {

                                self.errors = response.data.errors;
                                Object.keys(response.data.errors).map((key) => {
                                    self.errors[key] = response.data.errors[key][0];
                                });
                            }
                            self.$toast.open({
                                duration: 5000,
                                message: `Во время сохранения произошла какая-то ошибка !`,
                                position: 'is-bottom',
                                type: 'is-danger',
                                queue: false,
                            })
                        });
                },
                onSearch(search) {
                    let self = this;
                    axios.post(route('admin.users.search'), {
                        search: search
                    })
                        .then(function (response) {
                            self.data = response.data;
                            self.$snackbar.open({
                                duration: 5000,
                                message: `Поиск прошел успешно`,
                                position: 'is-bottom-left',
                                queue: false,
                            })
                        })
                        .catch(function (error) {
                            self.$toast.open({
                                duration: 5000,
                                message: `Во время поиска произошла какая-то ошибка !`,
                                position: 'is-bottom',
                                type: 'is-danger',
                                queue: false,
                            })
                        });
                }
            }
        });
    </script>
@endpush